---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: face-mapping
  namespace: faces
spec:
  hostname: "*"
  prefix: /face/
  service: face.faces
  timeout_ms: 250
  retry_policy:
    retry_on: 5xx
    num_retries: 1
  labels:
    emissary:
    - request_label_group:
      - x-emissary-test-allow:
        generic_key:
          key: mykey
          value: myvalue  
